name: hsifoodingr-compression
channels:
  - defaults
  - conda-forge
dependencies:
  - h5py[version='>=3.10']
  - numpy[version='>=1.26']
  - pillow[version='>=10']
  - pip
  - python=3.11
  - rich[version='>=13.7']
  - spectral[version='>=0.23']
  - tqdm[version='>=4.66']
  - typer[version='>=0.12']